spring:
  application:
    name: auth-server
  r2dbc:
    url: r2dbc:mysql://localhost:3306/auth_db
    username: groot
    password: iamgroot
    pool:
      enabled: true
  flyway:
    url: jdbc:mysql://localhost:3306/auth_db

logging:
  level:
    org.springframework.data.r2dbc: DEBUG

auth:
  config:
    jwt:
      expiry-in-min: 3
      signing-key: QPa1T?LZ;d=Ecpw?DTGa;exY$!*V!14) # dev signing key